sudo: false
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
before_install:
  # Use sed to replace the SSH URL with the public URL if .gitmodules exists
  - test -e ".gitmodules" && sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  # update the submodule in repo by manual
  - git submodule update --init --recursive
install:
  - npm install
script:
  - npm run test