version: "{build}"

environment:
  nodejs_version: "9"

matrix:
  fast_finish: true

install:
  - git clone https://github.com/laopo001/gltf-loader-ts.git src/third_party/gltf-loader-ts
  - choco install firefox
  - choco install googlechrome
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test
  - npm run test:browser
build: off