# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: |
    test -e ".gitmodules" && sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    git submodule update --init --recursive
    npm install
    npm run test
  displayName: 'test'
- script: |
    gulp version
  displayName: 'change version'

- task: npmAuthenticate@0
  displayName: 'npm Authenticate .npmrc'
  inputs:
    workingFile: .npmrc
    customEndpoint: dadigua
    
- task: Npm@1
  displayName: 'npm publish'
  inputs:
    command: publish
    verbose: false
    publishEndpoint: dadigua
